/**
 *
 *  AuthorBook.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "AuthorBook.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::librarybooks;

const std::string AuthorBook::Cols::_book_id = "book_id";
const std::string AuthorBook::Cols::_author_id = "author_id";
const std::vector<std::string> AuthorBook::primaryKeyName = {"book_id","author_id"};
const bool AuthorBook::hasPrimaryKey = true;
const std::string AuthorBook::tableName = "author_book";

const std::vector<typename AuthorBook::MetaData> AuthorBook::metaData_={
{"book_id","int32_t","integer",4,0,1,1},
{"author_id","int32_t","integer",4,0,1,1}
};
const std::string &AuthorBook::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
AuthorBook::AuthorBook(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["book_id"].isNull())
        {
            bookId_=std::make_shared<int32_t>(r["book_id"].as<int32_t>());
        }
        if(!r["author_id"].isNull())
        {
            authorId_=std::make_shared<int32_t>(r["author_id"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            bookId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            authorId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

AuthorBook::AuthorBook(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            bookId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            authorId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

AuthorBook::AuthorBook(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("book_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["book_id"].isNull())
        {
            bookId_=std::make_shared<int32_t>((int32_t)pJson["book_id"].asInt64());
        }
    }
    if(pJson.isMember("author_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["author_id"].isNull())
        {
            authorId_=std::make_shared<int32_t>((int32_t)pJson["author_id"].asInt64());
        }
    }
}

void AuthorBook::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            bookId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            authorId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

void AuthorBook::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("book_id"))
    {
        if(!pJson["book_id"].isNull())
        {
            bookId_=std::make_shared<int32_t>((int32_t)pJson["book_id"].asInt64());
        }
    }
    if(pJson.isMember("author_id"))
    {
        if(!pJson["author_id"].isNull())
        {
            authorId_=std::make_shared<int32_t>((int32_t)pJson["author_id"].asInt64());
        }
    }
}

const int32_t &AuthorBook::getValueOfBookId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(bookId_)
        return *bookId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &AuthorBook::getBookId() const noexcept
{
    return bookId_;
}
void AuthorBook::setBookId(const int32_t &pBookId) noexcept
{
    bookId_ = std::make_shared<int32_t>(pBookId);
    dirtyFlag_[0] = true;
}

const int32_t &AuthorBook::getValueOfAuthorId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(authorId_)
        return *authorId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &AuthorBook::getAuthorId() const noexcept
{
    return authorId_;
}
void AuthorBook::setAuthorId(const int32_t &pAuthorId) noexcept
{
    authorId_ = std::make_shared<int32_t>(pAuthorId);
    dirtyFlag_[1] = true;
}

void AuthorBook::updateId(const uint64_t id)
{
}
typename AuthorBook::PrimaryKeyType AuthorBook::getPrimaryKey() const
{
    return std::make_tuple(*bookId_,*authorId_);
}

const std::vector<std::string> &AuthorBook::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "book_id",
        "author_id"
    };
    return inCols;
}

void AuthorBook::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getBookId())
        {
            binder << getValueOfBookId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getAuthorId())
        {
            binder << getValueOfAuthorId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> AuthorBook::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void AuthorBook::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getBookId())
        {
            binder << getValueOfBookId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getAuthorId())
        {
            binder << getValueOfAuthorId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value AuthorBook::toJson() const
{
    Json::Value ret;
    if(getBookId())
    {
        ret["book_id"]=getValueOfBookId();
    }
    else
    {
        ret["book_id"]=Json::Value();
    }
    if(getAuthorId())
    {
        ret["author_id"]=getValueOfAuthorId();
    }
    else
    {
        ret["author_id"]=Json::Value();
    }
    return ret;
}

Json::Value AuthorBook::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getBookId())
            {
                ret[pMasqueradingVector[0]]=getValueOfBookId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getAuthorId())
            {
                ret[pMasqueradingVector[1]]=getValueOfAuthorId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getBookId())
    {
        ret["book_id"]=getValueOfBookId();
    }
    else
    {
        ret["book_id"]=Json::Value();
    }
    if(getAuthorId())
    {
        ret["author_id"]=getValueOfAuthorId();
    }
    else
    {
        ret["author_id"]=Json::Value();
    }
    return ret;
}

bool AuthorBook::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("book_id"))
    {
        if(!validJsonOfField(0, "book_id", pJson["book_id"], err, true))
            return false;
    }
    else
    {
        err="The book_id column cannot be null";
        return false;
    }
    if(pJson.isMember("author_id"))
    {
        if(!validJsonOfField(1, "author_id", pJson["author_id"], err, true))
            return false;
    }
    else
    {
        err="The author_id column cannot be null";
        return false;
    }
    return true;
}
bool AuthorBook::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool AuthorBook::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("book_id"))
    {
        if(!validJsonOfField(0, "book_id", pJson["book_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("author_id"))
    {
        if(!validJsonOfField(1, "author_id", pJson["author_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    return true;
}
bool AuthorBook::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool AuthorBook::validJsonOfField(size_t index,
                                  const std::string &fieldName,
                                  const Json::Value &pJson,
                                  std::string &err,
                                  bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
